[package]
name = "usta-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
ignore = { workspace = true }
fastembed = { workspace = true }
walkdir = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
usta-core = { path = "../usta-core" }
