name: Feature request
description: Suggest a feature or improvement.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: I want to ... but currently ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would the ideal behavior look like?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
